### ISSUE TITLE
Parameterize Command server port

### ISSUE THREAD

**Issue by EdHurtig** [openloopalliance/hyperloop-core#61]
Should be ale to set the Command server port `./core/core -i - -b 8363 -p 8364`

`-p` telemetry send port
`-b` bind command server 

or something like that.

**Comment by EdHurtig** [comment]
@shorstman @Dan-Hartman This is a good quick and easy one to tackle

**Comment by shorstman** [comment]
How are these values currently stored? I'm guessing they should become part of `args` that is already being used in parse_args()?

**Comment by EdHurtig** [comment]
Yep `parse_args` in [core/main.c](https://github.com/ParadigmHyperloop/hyperloop/tree/master/core/main.c) is where they should get parsed. Then they should either:

A) Get stored in the global `pod_t` as `logging_port` and `command_port` fields, then referenced from `command_main` [core/commander.c](https://github.com/ParadigmHyperloop/hyperloop/tree/master/core/commander.c) and `logging_main` [core/logging.c](https://github.com/ParadigmHyperloop/hyperloop/tree/master/core/logging.c)

OR

B) passed to the `command_main` and `logging_main` as args via `pthread_create`

OR 

C) Some other method I'm completely not thinking about

**Comment by shorstman** [comment]
`command_port` should be initialized as `#define CMD_SVR_PORT`? What about `logging_port`?

**Comment by EdHurtig** [comment]
`LOG_SVR_PORT` from [core/config.h](https://github.com/ParadigmHyperloop/hyperloop/tree/master/core/config.h)
